import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./page.module.css"
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={styles.main}>
          <Link href="/" className={styles.card}>Go Home</Link>
          {children}
        </main>
      </body>
    </html>
  );
}
